export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCES = "PRODUCT_LIST_SUCCES";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const PRODUCT_CATEGORY_REQUEST = "PRODUCT_CATEGORY_REQUEST";
export const PRODUCT_CATEGORY_SUCCES = "PRODUCT_CATEGORY_SUCCES";
export const PRODUCT_CATEGORY_FAIL = "PRODUCT_CATEGORY_FAIL";

export const PRODUCT_DETAIL_REQUEST = "PRODUCT_DETAIL_REQUEST";
export const PRODUCT_DETAIL_SUCCES = "PRODUCT_DETAIL_SUCCES";
export const PRODUCT_DETAIL_FAIL = "PRODUCT_DETAIL_FAIL";
